# Generated by Django 5.0.14 on 2025-06-09 10:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("bookings", "0004_remove_booking_room_group_delete_roomgroup"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Expense",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "expense_type",
                    models.CharField(
                        choices=[
                            ("flight", "Flight Tickets"),
                            ("accommodation", "Accommodation"),
                            ("activity", "Activity/Tour Cost"),
                            ("visa", "Visa Fees"),
                            ("insurance", "Travel Insurance"),
                            ("transport", "Local Transport"),
                            ("guide_fee", "Guide Fees"),
                            ("meals", "Meals & Food"),
                            ("commission", "Agent Commission"),
                            ("other", "Other"),
                        ],
                        help_text="Category of the expense (e.g., flight, accommodation).",
                        max_length=50,
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Amount of the expense in USD.",
                        max_digits=10,
                    ),
                ),
                (
                    "expense_date",
                    models.DateField(
                        help_text="The date the expense was incurred or recorded."
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Any internal notes or details about this expense.",
                    ),
                ),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                ("last_updated", models.DateTimeField(auto_now=True)),
                (
                    "booking",
                    models.ForeignKey(
                        help_text="The booking (participant) this expense is associated with.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="expenses",
                        to="bookings.booking",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="The user who created this expense record.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="expenses_created_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Expense",
                "verbose_name_plural": "Expenses",
                "ordering": ["-expense_date", "-date_created"],
            },
        ),
    ]
