# Generated by Django 5.0.14 on 2025-06-09 10:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("expenses", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ExpenseType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Name of the expense type (e.g., Flight Tickets, Accommodation).",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Brief description of this expense type."
                    ),
                ),
            ],
            options={
                "verbose_name": "Expense Type",
                "verbose_name_plural": "Expense Types",
                "ordering": ["name"],
            },
        ),
        migrations.AlterField(
            model_name="expense",
            name="expense_type",
            field=models.ForeignKey(
                help_text="Category of the expense (e.g., flight, accommodation).",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="expenses",
                to="expenses.expensetype",
            ),
        ),
    ]
