# Generated by Django 5.0.14 on 2025-06-08 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("customers", "0002_customer_passport_expiry_date_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customer",
            name="communication_history",
        ),
        migrations.RemoveField(
            model_name="customer",
            name="general_notes",
        ),
    ]
