# Generated by Django 5.0.14 on 2025-06-06 15:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("customers", "0001_initial"),
        ("trips", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Booking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("booking_date", models.DateTimeField(auto_now_add=True)),
                (
                    "internal_notes",
                    models.TextField(
                        blank=True, help_text="Internal notes specific to this booking."
                    ),
                ),
                (
                    "total_price",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        help_text="Automatically calculated total price of the booking (tier + add-ons).",
                        max_digits=10,
                    ),
                ),
                (
                    "amount_paid",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        help_text="Total amount paid by the customer for this booking.",
                        max_digits=10,
                    ),
                ),
                (
                    "booking_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Confirmation"),
                            ("confirmed", "Confirmed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        help_text="The overall status of the booking (e.g., Pending, Confirmed, Cancelled).",
                        max_length=20,
                    ),
                ),
                (
                    "payment_status",
                    models.CharField(
                        choices=[
                            ("not_paid", "Not Paid"),
                            ("partially_paid", "Partially Paid"),
                            ("fully_paid", "Fully Paid"),
                            ("refunded", "Refunded"),
                        ],
                        default="not_paid",
                        help_text="The payment status based on payments received.",
                        max_length=20,
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        help_text="The customer making this booking.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="bookings",
                        to="customers.customer",
                    ),
                ),
                (
                    "price_tier",
                    models.ForeignKey(
                        help_text="The chosen price tier for this booking.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="bookings",
                        to="trips.trippricetier",
                    ),
                ),
                (
                    "trip",
                    models.ForeignKey(
                        help_text="The trip the customer is booking.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="bookings",
                        to="trips.trip",
                    ),
                ),
            ],
            options={
                "verbose_name": "Booking",
                "verbose_name_plural": "Bookings",
                "ordering": ["-booking_date"],
                "unique_together": {("customer", "trip")},
            },
        ),
        migrations.CreateModel(
            name="BookingSelectedAddOn",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "add_on",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="trips.tripaddon",
                    ),
                ),
                (
                    "booking",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="selected_add_ons",
                        to="bookings.booking",
                    ),
                ),
            ],
            options={
                "verbose_name": "Selected Add-On",
                "verbose_name_plural": "Selected Add-Ons",
                "unique_together": {("booking", "add_on")},
            },
        ),
    ]
