# Generated by Django 5.0.14 on 2025-06-08 11:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="booking",
            name="internal_notes",
            field=models.TextField(
                blank=True,
                help_text="Internal notes specific to this booking (e.g. initial booking remarks). For communication log, use Booking Notes below.",
            ),
        ),
        migrations.CreateModel(
            name="BookingNote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "note_text",
                    models.TextField(
                        help_text="Details of the communication or internal note."
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "booking",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notes",
                        to="bookings.booking",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="booking_notes_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Booking Note",
                "verbose_name_plural": "Booking Notes",
                "ordering": ["timestamp"],
            },
        ),
    ]
