# Generated by Django 5.0.14 on 2025-06-08 12:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0002_alter_booking_internal_notes_bookingnote"),
        ("trips", "0002_trippricetier_room_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="RoomGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "room_type",
                    models.CharField(
                        choices=[
                            ("single", "Single Room"),
                            ("double", "Double Room"),
                            ("triple", "Triple Room"),
                            ("quad", "Quad Room"),
                            ("other", "Other"),
                        ],
                        help_text="The type of room (e.g., 'double', 'triple').",
                        max_length=10,
                    ),
                ),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                ("last_updated", models.DateTimeField(auto_now=True)),
                (
                    "trip",
                    models.ForeignKey(
                        help_text="The trip this room group belongs to.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="room_groups",
                        to="trips.trip",
                    ),
                ),
            ],
            options={
                "verbose_name": "Room Group",
                "verbose_name_plural": "Room Groups",
            },
        ),
        migrations.AddField(
            model_name="booking",
            name="room_group",
            field=models.ForeignKey(
                blank=True,
                help_text="The room group this booking belongs to (if applicable).",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="bookings",
                to="bookings.roomgroup",
            ),
        ),
    ]
