# Generated by Django 5.0.14 on 2025-06-08 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0003_roomgroup_booking_room_group"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="booking",
            name="room_group",
        ),
        migrations.DeleteModel(
            name="RoomGroup",
        ),
    ]
