# Generated by Django 5.0.14 on 2025-06-06 15:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Trip",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Unique name for the trip package.",
                        max_length=200,
                        unique=True,
                    ),
                ),
                (
                    "destination",
                    models.CharField(
                        blank=True,
                        help_text="Primary destination or region of the trip.",
                        max_length=255,
                    ),
                ),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                (
                    "internal_notes",
                    models.TextField(
                        blank=True,
                        help_text="Notes for internal staff only, not for customers.",
                    ),
                ),
                (
                    "detailed_itinerary",
                    models.TextField(
                        blank=True,
                        help_text="A comprehensive description of the trip itinerary.",
                    ),
                ),
                (
                    "max_capacity",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Maximum number of travelers this trip can accommodate.",
                        null=True,
                    ),
                ),
                (
                    "min_travelers",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Minimum number of travelers required for the trip to proceed.",
                        null=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Open for Booking"),
                            ("confirmed", "Confirmed"),
                            ("full", "Full"),
                            ("cancelled", "Cancelled"),
                            ("completed", "Completed"),
                        ],
                        default="open",
                        help_text="Current status of the trip (e.g., Open, Confirmed, Cancelled).",
                        max_length=20,
                    ),
                ),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                ("last_updated", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Trip",
                "verbose_name_plural": "Trips",
                "ordering": ["start_date", "name"],
                "unique_together": {("name", "start_date")},
            },
        ),
        migrations.CreateModel(
            name="TripAddOn",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="e.g., 'Airport Transfer', 'Optional Excursion'",
                        max_length=100,
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Price for this add-on in USD.",
                        max_digits=10,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Description of the add-on."
                    ),
                ),
                (
                    "trip",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="add_ons",
                        to="trips.trip",
                    ),
                ),
            ],
            options={
                "verbose_name": "Trip Add-On",
                "verbose_name_plural": "Trip Add-Ons",
                "ordering": ["price"],
                "unique_together": {("trip", "name")},
            },
        ),
        migrations.CreateModel(
            name="TripPriceTier",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="e.g., 'Standard', 'Premium', 'Early Bird'",
                        max_length=100,
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Price for this tier in USD.",
                        max_digits=10,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Description of what's included in this tier.",
                    ),
                ),
                (
                    "trip",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="price_tiers",
                        to="trips.trip",
                    ),
                ),
            ],
            options={
                "verbose_name": "Trip Price Tier",
                "verbose_name_plural": "Trip Price Tiers",
                "ordering": ["price"],
                "unique_together": {("trip", "name")},
            },
        ),
    ]
