# Generated by Django 5.0.14 on 2025-06-08 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trips", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="trippricetier",
            name="room_type",
            field=models.CharField(
                choices=[
                    ("single", "Single Room"),
                    ("double", "Double Room"),
                    ("triple", "Triple Room"),
                    ("quad", "Quad Room"),
                    ("other", "Other"),
                ],
                default="other",
                help_text="The type of rooming preference for this tier.",
                max_length=10,
            ),
        ),
    ]
