# Generated by Django 5.0.14 on 2025-06-08 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("trips", "0002_trippricetier_room_type"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="trippricetier",
            name="room_type",
        ),
    ]
